baseURL = "https://badayvedat.github.io"
languageCode = "en-us"
title = "Vedat Baday"
theme = "anubis"
paginate = 5

disqusShortname = ""
googleAnalytics = ""

[author]
name = "Vedat Baday"

[params]
author = "Vedat Baday"
description = "Anubis is a simple minimalist theme for Hugo blog engine."
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "auto"
readMore = false
readNextPosts = 2
copyCodeButton = true
math = true
creationYear = 2023

# Graphcomment support
graphcommentId = ""

# utteranc.es support
utterancesRepo = ""  # mandatory
utterancesTheme = "" # optional
utterancesIssue = "" # optional
utterancesLabel = "" # optional

[[params.colorScheme]]
# Enable toggle colorScheme
# Default to true
toggle = true
# Default colorScheme
# Default to auto
default = "auto"


[[params.social]]
id = "github"
url = "https://github.com/badayvedat"

[[params.social]]
id = "linkedin"
url = "https://linkedin.com/in/badayvedat"

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 3

[taxonomies]
tag = "tags"

[markup.goldmark.renderer]
unsafe = false

