name: Build and Deploy

on:
  push:
    branches: ["master"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          apt update &&
          apt-get install -y curl rsync build-essential
      - name: Download and Install smu
        run: |
          curl -o smu.tar.gz https://git.sr.ht/~bt/smu/archive/1544a3321b77255e193f0c044a8c32b09be99c50.tar.gz &&
          tar xzf smu.tar.gz ;
          cd smu-1544a3321b77255e193f0c044a8c32b09be99c50 && make install ;
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: make clean && make build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1