name: test2

on:
  issue_comment:
    types: [created, edited]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: my-second-step
        run: echo ${{ github.event.comment.body }}