name: Run tests

on:
  issue_comment:
    types: [created, edited]
  pull_request:
    branches: [master]

jobs:
  tests_a:
    if: contains(github.event.comment.body, '/hello_tests')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Execute a tests
        run: python tests/a.py
  job_b:
    if: |
      contains(github.event.comment.html_url, '/pull/') &&
      contains(github.event.comment.body, '/hello_tests')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Execute b tests
        run: |
          python tests/b.py
